- name: template
  template:
    src: exports
    dest: /etc/exports
  notify: restart nfs
- name: file
  file:
    path: "{{item}}"
    state: directory
    owner: www
    group: www
  loop:
    - "{{cloud_sf}}"
    - "{{wecenter_sf}}"
- name: systemd
  systemd:
    name: nfs
    state: started
